import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { cmsDataSchema } from '../schema/cms-data-schema.ts'
import type { SchemaDefinition, SchemaFieldDefinition, SchemaModelDefinition } from '../schema/dsl.ts'
import { buildSchemaSnapshot, compileSchemaSql, hashSchemaSnapshot } from '../db/schema-compiler.ts'

const rootDir = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const outputDir = path.resolve(rootDir, 'server/generated')

function toPascalCase(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function typeForField(field: SchemaFieldDefinition) {
  let base: string
  switch (field.kind) {
    case 'id':
    case 'int':
      base = 'number'
      break
    case 'boolean':
      base = 'boolean'
      break
    case 'datetime':
      base = 'Date'
      break
    case 'decimal':
      base = 'number'
      break
    case 'json':
      base = 'unknown'
      break
    case 'enum':
      base = field.enumValues?.map(value => `'${value}'`).join(' | ') || 'string'
      break
    default:
      base = 'string'
      break
  }

  return field.nullable ? `${base} | null` : base
}

function renderMetadata(definition: SchemaDefinition) {
  return `/* eslint-disable */
// Generated by generator/generate-db-artifacts.ts
import type { GeneratedSchema } from '#modula/server/data/runtime/types'

export const generatedSchema = ${JSON.stringify(definition, null, 2)} satisfies GeneratedSchema
`
}

function renderBootstrapArtifacts(definition: SchemaDefinition) {
  const snapshot = buildSchemaSnapshot(definition)
  const schemaHash = hashSchemaSnapshot(snapshot)
  const sqliteBootstrapSql = compileSchemaSql(definition, 'sqlite')
  const d1BootstrapSql = compileSchemaSql(definition, 'd1')
  const postgresBootstrapSql = compileSchemaSql(definition, 'postgres')
  const mysqlBootstrapSql = compileSchemaSql(definition, 'mysql')

  return `/* eslint-disable */
// Generated by generator/generate-db-artifacts.ts

export const schemaSnapshot = ${JSON.stringify(snapshot, null, 2)} as const
export const schemaSnapshotHash = '${schemaHash}'
export const sqliteBootstrapSql = ${JSON.stringify(sqliteBootstrapSql)}
export const d1BootstrapSql = ${JSON.stringify(d1BootstrapSql)}
export const postgresBootstrapSql = ${JSON.stringify(postgresBootstrapSql)}
export const mysqlBootstrapSql = ${JSON.stringify(mysqlBootstrapSql)}
`
}

function renderModelTypes(definition: SchemaDefinition) {
  const lines: string[] = [
    '/* eslint-disable */',
    '// Generated by generator/generate-db-artifacts.ts',
    '',
    "import type { QueryWhereInput, QueryOrderByInput, QuerySelectShape, QueryIncludeShape } from '#modula/server/data/runtime/types'",
    ''
  ]

  const modelNames = Object.keys(definition.models)
  for (const modelName of modelNames) {
    const model = definition.models[modelName] as SchemaModelDefinition
    const recordName = `${toPascalCase(modelName)}Record`
    const whereName = `${toPascalCase(modelName)}WhereInput`
    const createName = `${toPascalCase(modelName)}CreateInput`
    const updateName = `${toPascalCase(modelName)}UpdateInput`
    const selectName = `${toPascalCase(modelName)}Select`
    const includeName = `${toPascalCase(modelName)}Include`
    const orderByName = `${toPascalCase(modelName)}OrderByInput`

    lines.push(`export interface ${recordName} {`)
    for (const [fieldName, field] of Object.entries(model.fields)) {
      lines.push(`  ${fieldName}: ${typeForField(field)}`)
    }
    lines.push('}')
    lines.push('')

    lines.push(`export type ${whereName} = QueryWhereInput<${recordName}>`)
    lines.push(`export type ${createName} = Partial<${recordName}> & Pick<${recordName}, ${Object.entries(model.fields).filter(([, field]) => !field.nullable && field.default === undefined && field.kind !== 'id').map(([fieldName]) => `'${fieldName}'`).join(' | ') || 'never'}>`)
    lines.push(`export type ${updateName} = Partial<Omit<${recordName}, '${model.primaryKey || 'id'}'>>`)
    lines.push(`export type ${selectName} = QuerySelectShape<${recordName}>`)

    const relationEntries = Object.keys(model.relations || {})
    if (relationEntries.length) {
      lines.push(`export type ${includeName} = QueryIncludeShape<${relationEntries.map((name) => `'${name}'`).join(' | ')}>`)
    } else {
      lines.push(`export type ${includeName} = QueryIncludeShape<never>`)
    }
    lines.push(`export type ${orderByName} = QueryOrderByInput<${recordName}>`)
    lines.push('')
  }

  lines.push(`export type GeneratedModelName = ${modelNames.map(name => `'${name}'`).join(' | ')}`)
  lines.push('')
  return lines.join('\n')
}

fs.mkdirSync(outputDir, { recursive: true })
fs.writeFileSync(path.resolve(outputDir, 'schema.generated.ts'), renderMetadata(cmsDataSchema), 'utf8')
fs.writeFileSync(path.resolve(outputDir, 'models.generated.ts'), renderModelTypes(cmsDataSchema), 'utf8')
fs.writeFileSync(path.resolve(outputDir, 'bootstrap.generated.ts'), renderBootstrapArtifacts(cmsDataSchema), 'utf8')
console.log('Generated DB artifacts in server/generated')
