ALTER TABLE "Product" ADD COLUMN "stock" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "allowOfflinePayment" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Product" ADD COLUMN "allowOnlinePayment" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ProductLot" ADD COLUMN "allowOfflinePayment" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "ProductLot" ADD COLUMN "allowOnlinePayment" INTEGER NOT NULL DEFAULT 0;
