import crypto from 'node:crypto'
import type {
  SchemaDefinition,
  SchemaFieldDefinition,
  SchemaModelDefinition,
  SchemaOnDeleteAction,
  SchemaRelationDefinition
} from '../schema/dsl.ts'

export type SchemaDialect = 'sqlite' | 'd1' | 'postgres' | 'mysql'

export interface SchemaSnapshot {
  models: Record<string, SchemaModelDefinition>
}

interface DialectOptions {
  dialect: SchemaDialect
  quoteIdentifier(identifier: string): string
  escapeString(value: string): string
}

function sortObject<T>(input: Record<string, T>) {
  return Object.fromEntries(
    Object.entries(input).sort(([left], [right]) => left.localeCompare(right))
  )
}

function normalizeModel(model: SchemaModelDefinition): SchemaModelDefinition {
  const normalizedRelations = model.relations
    ? sortObject(
        Object.fromEntries(
          Object.entries(model.relations).map(([key, relation]) => [
            key,
            {
              ...relation,
              onDelete: relation.onDelete || 'noAction'
            }
          ])
        )
      )
    : undefined

  const normalizedIndexes = (model.indexes || [])
    .map(index => ({
      ...index,
      fields: [...index.fields]
    }))
    .sort((left, right) => {
      const leftKey = `${left.unique ? '1' : '0'}:${left.name || ''}:${left.fields.join(',')}`
      const rightKey = `${right.unique ? '1' : '0'}:${right.name || ''}:${right.fields.join(',')}`
      return leftKey.localeCompare(rightKey)
    })

  return {
    tableName: model.tableName,
    primaryKey: model.primaryKey,
    fields: sortObject(model.fields),
    relations: normalizedRelations,
    indexes: normalizedIndexes
  }
}

export function buildSchemaSnapshot(schema: SchemaDefinition): SchemaSnapshot {
  return {
    models: sortObject(
      Object.fromEntries(
        Object.entries(schema.models).map(([modelName, model]) => [modelName, normalizeModel(model)])
      )
    )
  }
}

export function hashSchemaSnapshot(snapshot: SchemaSnapshot) {
  return crypto
    .createHash('sha256')
    .update(JSON.stringify(snapshot))
    .digest('hex')
}

function quoteString(options: DialectOptions, value: string) {
  return `'${options.escapeString(value)}'`
}

function renderEnumCheck(options: DialectOptions, fieldName: string, field: SchemaFieldDefinition) {
  if (field.kind !== 'enum' || !field.enumValues?.length) {
    return ''
  }

  const values = field.enumValues.map(value => quoteString(options, value)).join(', ')
  return ` CHECK (${options.quoteIdentifier(fieldName)} IN (${values}))`
}

function renderDefaultValue(options: DialectOptions, field: SchemaFieldDefinition) {
  if (field.default === undefined || field.default === 'autoincrement') {
    return ''
  }

  if (field.default === 'now') {
    switch (options.dialect) {
      case 'postgres':
        return ' DEFAULT CURRENT_TIMESTAMP'
      default:
        return ' DEFAULT CURRENT_TIMESTAMP'
    }
  }

  if (typeof field.default === 'boolean') {
    switch (options.dialect) {
      case 'sqlite':
      case 'd1':
        return ` DEFAULT ${field.default ? 1 : 0}`
      default:
        return ` DEFAULT ${field.default ? 'TRUE' : 'FALSE'}`
    }
  }

  if (typeof field.default === 'number') {
    return ` DEFAULT ${field.default}`
  }

  if (field.default === null) {
    return ' DEFAULT NULL'
  }

  return ` DEFAULT ${quoteString(options, String(field.default))}`
}

function renderType(options: DialectOptions, fieldName: string, field: SchemaFieldDefinition, primaryKey: string) {
  if (fieldName === primaryKey && field.kind === 'id') {
    switch (options.dialect) {
      case 'postgres':
        return 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
      case 'mysql':
        return 'INT AUTO_INCREMENT PRIMARY KEY'
      default:
        return 'INTEGER PRIMARY KEY AUTOINCREMENT'
    }
  }

  switch (options.dialect) {
    case 'postgres':
      switch (field.kind) {
        case 'id':
        case 'int':
          return 'INTEGER'
        case 'boolean':
          return 'BOOLEAN'
        case 'datetime':
          return 'TIMESTAMP'
        case 'decimal':
          return 'NUMERIC'
        case 'json':
          return 'JSONB'
        case 'enum':
          return 'TEXT'
        default:
          return 'TEXT'
      }
    case 'mysql':
      switch (field.kind) {
        case 'id':
        case 'int':
          return 'INT'
        case 'boolean':
          return 'BOOLEAN'
        case 'datetime':
          return 'DATETIME'
        case 'decimal':
          return 'DECIMAL(12, 2)'
        case 'json':
          return 'JSON'
        case 'enum':
          return 'VARCHAR(191)'
        default:
          return 'VARCHAR(191)'
      }
    default:
      switch (field.kind) {
        case 'id':
        case 'int':
          return 'INTEGER'
        case 'boolean':
          return 'INTEGER'
        case 'datetime':
          return 'TEXT'
        case 'decimal':
          return 'NUMERIC'
        case 'json':
          return 'TEXT'
        case 'enum':
          return 'TEXT'
        default:
          return 'TEXT'
      }
  }
}

function renderColumn(options: DialectOptions, fieldName: string, field: SchemaFieldDefinition, primaryKey: string) {
  const columnName = options.quoteIdentifier(fieldName)
  const typeSql = renderType(options, fieldName, field, primaryKey)
  const nullableSql = fieldName === primaryKey || field.nullable ? '' : ' NOT NULL'
  const uniqueSql = fieldName !== primaryKey && field.unique ? ' UNIQUE' : ''
  const defaultSql = renderDefaultValue(options, field)
  const enumCheck = renderEnumCheck(options, fieldName, field)
  return `${columnName} ${typeSql}${nullableSql}${uniqueSql}${defaultSql}${enumCheck}`
}

function renderOnDelete(action: SchemaOnDeleteAction | undefined) {
  switch (action) {
    case 'cascade':
      return ' ON DELETE CASCADE'
    case 'setNull':
      return ' ON DELETE SET NULL'
    case 'restrict':
      return ' ON DELETE RESTRICT'
    default:
      return ''
  }
}

function renderForeignKeys(options: DialectOptions, relations: Record<string, SchemaRelationDefinition> | undefined, targetTables: Record<string, SchemaModelDefinition>) {
  if (!relations) return []

  return Object.values(relations).map((relation) => {
    const targetModel = targetTables[relation.target]
    const targetTableName = targetModel?.tableName || relation.target
    return `FOREIGN KEY (${options.quoteIdentifier(relation.foreignKey)}) REFERENCES ${options.quoteIdentifier(targetTableName)} (${options.quoteIdentifier(relation.references)})${renderOnDelete(relation.onDelete)}`
  })
}

function dedupeIndexes(model: SchemaModelDefinition) {
  const fieldUniqueKeys = new Set(
    Object.entries(model.fields)
      .filter(([, field]) => field.unique)
      .map(([fieldName]) => `U:${fieldName}`)
  )

  return (model.indexes || []).filter((index) => {
    if (!index.unique || index.fields.length !== 1) return true
    return !fieldUniqueKeys.has(`U:${index.fields[0]}`)
  })
}

function renderCreateTable(options: DialectOptions, modelName: string, model: SchemaModelDefinition, allModels: Record<string, SchemaModelDefinition>) {
  const tableName = options.quoteIdentifier(model.tableName || modelName)
  const primaryKey = model.primaryKey || 'id'
  const columns = Object.entries(model.fields).map(([fieldName, field]) => renderColumn(options, fieldName, field, primaryKey))
  const foreignKeys = renderForeignKeys(options, model.relations, allModels)
  return [
    `CREATE TABLE IF NOT EXISTS ${tableName} (`,
    [...columns, ...foreignKeys].map(line => `  ${line}`).join(',\n'),
    ');'
  ].join('\n')
}

function renderIndex(options: DialectOptions, modelName: string, model: SchemaModelDefinition, fields: string[], indexName: string | undefined, unique: boolean | undefined) {
  const tableName = options.quoteIdentifier(model.tableName || modelName)
  const resolvedName = indexName || `${modelName}_${fields.join('_')}_${unique ? 'uniq' : 'idx'}`
  return `CREATE ${unique ? 'UNIQUE ' : ''}INDEX IF NOT EXISTS ${options.quoteIdentifier(resolvedName)} ON ${tableName} (${fields.map(field => options.quoteIdentifier(field)).join(', ')});`
}

function createDialectOptions(dialect: SchemaDialect): DialectOptions {
  return {
    dialect,
    quoteIdentifier(identifier) {
      switch (dialect) {
        case 'mysql':
          return `\`${identifier.replaceAll('`', '``')}\``
        default:
          return `"${identifier.replaceAll('"', '""')}"`
      }
    },
    escapeString(value) {
      return value.replaceAll("'", "''")
    }
  }
}

export function compileSchemaSql(schema: SchemaDefinition, dialect: SchemaDialect) {
  const options = createDialectOptions(dialect)
  const snapshot = buildSchemaSnapshot(schema)
  const statements: string[] = []

  for (const [modelName, model] of Object.entries(snapshot.models)) {
    statements.push(renderCreateTable(options, modelName, model, snapshot.models))
  }

  for (const [modelName, model] of Object.entries(snapshot.models)) {
    for (const indexDefinition of dedupeIndexes(model)) {
      statements.push(renderIndex(options, modelName, model, indexDefinition.fields, indexDefinition.name, indexDefinition.unique))
    }
  }

  return `${statements.join('\n\n')}\n`
}

export function diffSchemaSnapshots(previousSnapshot: SchemaSnapshot | null, nextSnapshot: SchemaSnapshot) {
  if (!previousSnapshot) {
    return {
      addedModels: Object.keys(nextSnapshot.models),
      removedModels: [] as string[],
      changedModels: [] as Array<{ model: string; changes: string[] }>
    }
  }

  const addedModels = Object.keys(nextSnapshot.models).filter(modelName => !previousSnapshot.models[modelName])
  const removedModels = Object.keys(previousSnapshot.models).filter(modelName => !nextSnapshot.models[modelName])
  const changedModels: Array<{ model: string; changes: string[] }> = []

  for (const modelName of Object.keys(nextSnapshot.models)) {
    const previousModel = previousSnapshot.models[modelName]
    const nextModel = nextSnapshot.models[modelName]
    if (!previousModel || !nextModel) continue

    const changes: string[] = []
    const previousFields = previousModel.fields
    const nextFields = nextModel.fields

    for (const fieldName of Object.keys(nextFields)) {
      if (!previousFields[fieldName]) {
        changes.push(`field added: ${fieldName}`)
        continue
      }

      if (JSON.stringify(previousFields[fieldName]) !== JSON.stringify(nextFields[fieldName])) {
        changes.push(`field changed: ${fieldName}`)
      }
    }

    for (const fieldName of Object.keys(previousFields)) {
      if (!nextFields[fieldName]) {
        changes.push(`field removed: ${fieldName}`)
      }
    }

    if (JSON.stringify(previousModel.relations || {}) !== JSON.stringify(nextModel.relations || {})) {
      changes.push('relations changed')
    }

    if (JSON.stringify(previousModel.indexes || []) !== JSON.stringify(nextModel.indexes || [])) {
      changes.push('indexes changed')
    }

    if (changes.length) {
      changedModels.push({ model: modelName, changes })
    }
  }

  return {
    addedModels,
    removedModels,
    changedModels
  }
}
